### ISSUE TITLE
Broken for non svg images

### ISSUE THREAD

**Issue by tvdeyen** [tomasc/dragonfly_svg#9]
In #4 I fixed support for non svg images. #8 removed this fix and now this plugin is broken again.

**Comment by tomasc** [comment]
@tvdeyen ah thanks.
I wonder if we should come up with some pattern for all dragonfly plugins to handle fallbacks? Esp since we now have the SUPPORTED_FORMATS constants.

**Comment by tvdeyen** [comment]
I'm pretty sure https://github.com/tomasc/dragonfly_svg/blob/9e6b5812e27aecb1b408b50629f8fab48621d538/lib/dragonfly_svg/analysers/svg_properties.rb#L7 is the culprit.

We would need to call other plugins for the same analyser. Ideally dragonfly would chain analysers or provide fallbacks. The problem is that dragonfly has no support for duplicated analysers. We will need to fix this on our end.

**Comment by tomasc** [comment]
Maybe we should do that for Dragonfly?

**Comment by tomasc** [comment]
So that one could simply call super?

**Comment by trevorsmith** [comment]
This is also a problem for us – our app allows users to upload both images and SVGs, and this plugin now clobbers the width/height/other analysers defined by the ImageMagick plugin.

Downgrading to 0.0.4 fixed the issue.

**Comment by tomasc** [comment]
Hi @tvdeyen & @trevorsmith ,
Thanks for reporting the issue.

I gave it some more thought and I will not fix it in the plugin – the reason being that since there is no generic way (for example to call `super`) in Dragonfly, we would potentially have to check for all possibilities and alternatives (look at my other Dragonfly plugins, there's potentially many more collisions – for example with `thumb` processor etc.). And that's out of scope here.

The way we solved it in our app is by making a custom analysers/processors that check for mime or ext and re-route to corresponding Dragonfly analyser/processor. This works just fine.

Long term, I think it would be great if Dragonfly itself would implement the possibility to call `super` from an analyser/processor/generator for example like this:

```ruby
def call(content)
  return super(content) unless content.mime_type == DragonflySvg::SVG_MIME_TYPE
end
```

I am closing this issue as `wontfix`.
Tomas
